import React from 'react';
import { ArrowLeft, Printer, Clock, MapPin, CreditCard, ShoppingBag, ChevronRight, Phone, MessageSquare, Truck, Settings, FileText, Store, RefreshCw } from 'lucide-react';
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0));
const date=value=>value?new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}):'—';
const labels={pending:'Recebido',confirmed:'Aceito',preparing:'Em preparo',shipped:'Saiu p/ entrega',delivered:'Entregue',cancelled:'Cancelado'};
const payments={pix:'PIX',credit_card:'Cartão de crédito',debit_card:'Cartão de débito',cash:'Dinheiro',split:'Pagamento dividido',whatsapp:'WhatsApp',bank_transfer:'Transferência',to_arrange:'A combinar'};
const origins={catalog:'Catálogo',pdv_balcao:'Balcão',pdv_quick:'Venda rápida',pdv_table:'Mesa',pdv_pickup:'Retirada PDV',pdv_delivery:'Delivery PDV'};
const flow=['pending','confirmed','preparing','shipped','delivered'];
function Badge({order}){return <span className={`orders-badge ${order.status}`}>{labels[order.status]||order.status}</span>;}
function Alerts({order}){return <>{!order.viewed_by_admin&&<span className="orders-flag">Novo pedido</span>}{order.edited_by_customer&&<span className="orders-flag edited">Alterado pelo cliente</span>}</>;}
export function OrderCards({orders,onOpen,focusOrderId}){
 return <><div className="orders-card-grid">{orders.map(order=><button type="button" key={order.id} onClick={()=>onOpen(order)} className={`orders-list-card ${focusOrderId===order.id?'focused':''}`}>
 <div className="orders-card-heading"><strong>#{order.order_number}</strong><Badge order={order}/></div><p className="orders-customer">{order.customer_name||'Cliente'}</p><Alerts order={order}/>
 <div className="orders-card-meta"><span><Clock size={15}/>{date(order.created_date)}</span><ChevronRight size={18}/></div>
 <p className="orders-card-meta"><Store size={15}/>{origins[order.sale_origin]||'Catálogo'}</p><div className="orders-card-meta"><span><CreditCard size={15}/>{payments[order.payment_method]||order.payment_method}</span><strong className="orders-price">{money(order.total)}</strong></div>
 </button>)}</div>{!orders.length&&<p className="orders-empty">Nenhum pedido encontrado</p>}</>;
}
export function OrderKanbanCard({order,onStatusChange,onOpen}){
 const next=flow[flow.indexOf(order.status)+1];const actions={pending:'Aceitar',confirmed:'Iniciar preparo',preparing:'Saiu p/ entrega',shipped:'Marcar entregue'};
 return <article className="orders-board-card"><button type="button" className="orders-board-open" onClick={()=>onOpen(order)}>
 <div className="orders-card-heading"><strong>#{order.order_number}</strong><time>{date(order.created_date).split(', ').pop()}</time></div><p className="orders-customer">{order.customer_name||'Cliente'}</p><Alerts order={order}/>
 <p className="orders-card-meta"><Truck size={15}/>{order.delivery_method==='pickup'?'Retirada':'Delivery'}<ChevronRight size={16} className="ml-auto"/></p>
 <p className="orders-card-meta"><MapPin size={15}/>{order.delivery_neighborhood||order.delivery_city||'Endereço nos detalhes'}</p>
 <div className="orders-card-meta"><span><ShoppingBag size={15}/>{order.items?.reduce((sum,item)=>sum+Number(item.quantity||0),0)||0} itens</span><strong className="orders-price">{money(order.total)}</strong></div></button>
 <div className="orders-board-actions"><button type="button" onClick={()=>onOpen(order)}>Ver</button>{next?<button type="button" className={`next ${order.status}`} onClick={()=>onStatusChange(order.id,next)}>{actions[order.status]}</button>:<button type="button" className="next delivered" onClick={()=>onOpen(order)}>Ver detalhes</button>}</div></article>;
}
function Info({icon:Icon,label,children}){return <div className="orders-info"><Icon size={22}/><div><small>{label}</small><div>{children||'Não informado'}</div></div></div>;}
function Panel({icon:Icon,title,children}){return <section className="orders-panel"><h2><span><Icon size={23}/></span>{title}</h2>{children}</section>;}
function printOrder(order){
 const receipt=window.open('','_blank','width=800,height=700');if(!receipt)return;
 receipt.document.title=`Pedido #${order.order_number}`;
 const title=receipt.document.createElement('h1');title.textContent=`Pedido #${order.order_number}`;receipt.document.body.append(title);
 const lines=[order.customer_name,date(order.created_date),order.customer_phone,order.delivery_address,order.delivery_neighborhood,order.delivery_city,order.delivery_zip,order.delivery_notes,`Status: ${labels[order.status]}`,`Pagamento: ${payments[order.payment_method]||order.payment_method}`,`Origem: ${origins[order.sale_origin]||'Catálogo'}`,
 ...(order.items||[]).flatMap(item=>[`${item.quantity}x ${item.product_name} ${item.variation||''} — ${money(item.unit_price*item.quantity)}`,...(item.addons||[]).map(a=>typeof a==='string'?a:a.name),item.notes]),order.order_notes,order.admin_notes,`Desconto: ${money(order.discount)}`,`Entrega: ${money(order.delivery_fee)}`,`Total: ${money(order.total)}`];
 for(const line of lines.filter(Boolean)){const p=receipt.document.createElement('p');p.textContent=line;receipt.document.body.append(p);}receipt.document.close();receipt.focus();receipt.print();
}
export function OrderDetails({order,deliverers,onBack,onStatusChange,onAssign,onEdit,messageAction}){
 return <div className="orders-details"><header className="orders-detail-top"><div><h1>Detalhes do pedido</h1><p>Visualize e gerencie todas as informações deste pedido.</p></div><div className="orders-top-actions"><button type="button" onClick={onBack}><ArrowLeft size={18}/>Voltar para pedidos</button><button type="button" className="primary" onClick={()=>printOrder(order)}><Printer size={18}/>Imprimir pedido</button></div></header>
 <div className="orders-detail-layout"><div className="orders-detail-main"><section className="orders-panel"><div className="orders-detail-identity"><span className="orders-detail-icon"><FileText size={27}/></span><div><h2>Pedido #{order.order_number}</h2><p>{order.customer_name}</p></div><div className="orders-detail-status"><Badge order={order}/><small>Realizado em {date(order.created_date)}</small></div></div><Alerts order={order}/>
 <div className="orders-info-grid"><div><Info icon={Clock} label="Data e hora">{date(order.created_date)}</Info><Info icon={Store} label="Origem">{origins[order.sale_origin]||'Catálogo'}</Info><Info icon={Phone} label="Telefone">{order.customer_phone}</Info><Info icon={MessageSquare} label="Referência">{order.delivery_notes}</Info></div><div><Info icon={MapPin} label="Endereço">{order.delivery_method==='pickup'?'Retirada no estabelecimento':[order.delivery_address,order.delivery_city].filter(Boolean).join(', ')}</Info><Info icon={MapPin} label="Bairro e CEP">{[order.delivery_neighborhood,order.delivery_zip&&`CEP: ${order.delivery_zip}`].filter(Boolean).join(' • ')}</Info>{order.customer_email&&<Info icon={MessageSquare} label="E-mail">{order.customer_email}</Info>}</div></div></section>
 <Panel icon={ShoppingBag} title="Itens do pedido"><div className="orders-items"><div className="orders-item-row heading"><span>Item</span><span>Qtd</span><span>Valor unit.</span><span>Subtotal</span></div>{order.items?.map((item,index)=><div key={index} className="orders-item-row"><div><strong>{item.product_name}</strong>{item.variation&&<small>{item.variation}</small>}{item.addons?.length>0&&<small>+ {item.addons.map(a=>typeof a==='string'?a:a.name).join(', ')}</small>}{item.notes&&<small>{item.notes}</small>}{item.custom_fields&&Object.entries(item.custom_fields).map(([key,value])=><small key={key}>{key}: {String(value)}</small>)}</div><span>{item.quantity}</span><span>{money(item.unit_price)}</span><strong>{money(item.unit_price*item.quantity)}</strong></div>)}</div>
 {order.discount>0&&<p className="orders-total-line discount"><span>Desconto</span><span>- {money(order.discount)}</span></p>}<p className="orders-total-line"><span>Frete</span><span>{money(order.delivery_fee)}</span></p><div className="orders-final-total"><strong>Total do pedido</strong><strong>{money(order.total)}</strong></div>{order.order_notes&&<p className="orders-note">Observações: {order.order_notes}</p>}{order.admin_notes&&<p className="orders-note">Notas do gestor: {order.admin_notes}</p>}</Panel></div>
 <aside className="orders-detail-side"><Panel icon={CreditCard} title="Resumo do pedido"><strong className="orders-grand-total">{money(order.total)}</strong><div className="orders-payment-summary"><Info icon={CreditCard} label="Método de pagamento">{payments[order.payment_method]||order.payment_method}</Info><Info icon={Clock} label="Status do pagamento"><span className={`orders-badge ${order.payment_status==='paid'?'delivered':'pending'}`}>{order.payment_status==='paid'?'Pago':'Pendente'}</span></Info></div>{order.payment_method==='split'&&Object.entries(order.split_payments||{}).map(([method,value])=><p className="orders-total-line" key={method}><span>{payments[method]||method}</span><span>{money(value)}</span></p>)}{order.change_for>0&&<p>Troco para {money(order.change_for)}</p>}</Panel>
 <Panel icon={Truck} title="Entrega"><label className="orders-field-label">Atribuir entregador</label>{order.delivery_method==='pickup'?<p>Retirada no estabelecimento</p>:<select aria-label="Atribuir entregador" value={deliverers.find(d=>d.name===order.tracking_code)?.id||''} onChange={e=>onAssign(order.id,e.target.value)}><option value="">— Nenhum —</option>{deliverers.map(d=><option key={d.id} value={d.id}>{d.name} ({d.vehicle})</option>)}</select>}</Panel>
 <Panel icon={RefreshCw} title="Atualizar status"><div className="orders-status-actions">{flow.map(status=><button type="button" key={status} aria-pressed={order.status===status} className={order.status===status?'active':''} onClick={()=>onStatusChange(order.id,status)}>{labels[status]}</button>)}<button type="button" className="cancel" onClick={()=>onStatusChange(order.id,'cancelled')}>Cancelar</button></div></Panel>
 <Panel icon={Settings} title="Ações do pedido"><div className="orders-detail-actions">{messageAction}<button type="button" onClick={()=>onEdit(order)}><Settings size={18}/>Editar valores / pagamento</button><button type="button" onClick={()=>printOrder(order)}><Printer size={18}/>Imprimir pedido</button></div></Panel></aside></div></div>;
}
