import React,{useEffect,useRef,useState}from'react';
import{CalendarDays,Copy,Eye,GripVertical,Megaphone,Pencil,Plus,Save,Trash2,X}from'lucide-react';
import{base44}from'@/api/base44Client';
const fresh=()=>({id:crypto.randomUUID(),text:'',is_active:true,start_date:'',end_date:'',sort_order:0});
const fmt=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'';
const period=m=>m.start_date||m.end_date?`${fmt(m.start_date)||'Início imediato'} – ${fmt(m.end_date)||'sem data final'}`:'Início imediato • sem data final';
function Toggle({value,onClick}){return <button type="button" onClick={onClick} className={`relative h-7 w-24 rounded-lg text-[11px] font-bold ${value?'bg-emerald-500 text-emerald-900':'bg-red-100 text-red-500'}`}><i className={`absolute top-1 h-5 w-5 rounded-md bg-white shadow ${value?'left-[72px]':'left-1'}`}/><span className={value?'pr-5':'pl-5'}>{value?'Ativo':'Inativo'}</span></button>}
export default function PromoMessageManager({store,onStoreChange}){const[messages,setMessages]=useState(store?.promo_messages||[]),[editing,setEditing]=useState(),[preview,setPreview]=useState(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[textColor,setTextColor]=useState(store?.promo_ticker_text_color||'#111827'),[backgroundColor,setBackgroundColor]=useState(store?.promo_ticker_background_color||'#FFF7ED');const drag=useRef();
 useEffect(()=>setMessages(store?.promo_messages||[]),[store?.promo_messages]);
 useEffect(()=>{setTextColor(store?.promo_ticker_text_color||'#111827');setBackgroundColor(store?.promo_ticker_background_color||'#FFF7ED')},[store?.promo_ticker_text_color,store?.promo_ticker_background_color]);
 const persist=async rows=>{if(!store?.id)return;setBusy(true);setError('');const next=rows.map((m,i)=>({...m,sort_order:i}));try{const saved=await base44.entities.Store.update(store.id,{promo_messages:next});setMessages(next);onStoreChange?.(p=>({...p,...saved,promo_messages:next}))}catch(e){setError(e.message||'Não foi possível salvar.')}finally{setBusy(false)}};
 const save=async()=>{if(!editing?.text?.trim())return;const exists=messages.some(m=>m.id===editing.id);await persist(exists?messages.map(m=>m.id===editing.id?{...editing,text:editing.text.trim()}:m):[...messages,{...editing,text:editing.text.trim()}]);setEditing()};
 const move=(from,to)=>{if(from==null||from===to)return;const next=[...messages],item=next.splice(from,1)[0];next.splice(to,0,item);persist(next)};
 const saveColors=async()=>{if(!store?.id)return;setBusy(true);setError('');try{const saved=await base44.entities.Store.update(store.id,{promo_ticker_text_color:textColor,promo_ticker_background_color:backgroundColor});onStoreChange?.(p=>({...p,...saved,promo_ticker_text_color:textColor,promo_ticker_background_color:backgroundColor}))}catch(e){setError(e.message||'Não foi possível salvar as cores.')}finally{setBusy(false)}};
 return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><header className="flex flex-wrap items-center justify-between gap-3 p-5"><div className="flex items-start gap-3"><Megaphone size={27}/><div><h2 className="font-bold text-slate-950">Faixa promocional do topo</h2><p className="mt-1 text-sm text-slate-500">Letreiro exibido abaixo da busca e acima do banner principal.</p></div></div><button onClick={()=>setEditing(fresh())} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-emerald-500 px-5 text-sm font-bold text-white"><Plus size={16}/>Nova mensagem</button></header>{error&&<p className="mx-5 mb-3 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="flex flex-wrap items-end gap-4 border-t border-slate-100 bg-slate-50/60 px-5 py-4"><label className="text-xs font-semibold text-slate-600">Cor do texto<span className="mt-1 flex items-center gap-2"><input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)} className="h-10 w-12 rounded border bg-white p-1"/><input value={textColor} onChange={e=>setTextColor(e.target.value)} className="h-10 w-28 rounded-lg border px-2 font-mono text-xs"/></span></label><label className="text-xs font-semibold text-slate-600">Cor de fundo<span className="mt-1 flex items-center gap-2"><input type="color" value={backgroundColor} onChange={e=>setBackgroundColor(e.target.value)} className="h-10 w-12 rounded border bg-white p-1"/><input value={backgroundColor} onChange={e=>setBackgroundColor(e.target.value)} className="h-10 w-28 rounded-lg border px-2 font-mono text-xs"/></span></label><button onClick={saveColors} disabled={busy} className="min-h-10 rounded-lg bg-slate-900 px-4 text-xs font-bold text-white disabled:opacity-50">Salvar cores</button><div className="min-w-[220px] flex-1 overflow-hidden rounded-lg px-4 py-2 text-center text-xs font-semibold" style={{color:textColor,backgroundColor}}>{messages[0]?.text||'Prévia do letreiro promocional'}</div></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th/><th className="p-3">Mensagem</th><th className="p-3">Período de exibição</th><th className="p-3">Status</th><th className="p-3 text-right">Ações</th></tr></thead><tbody>{messages.map((m,i)=><tr key={m.id} draggable onDragStart={()=>drag.current=i} onDragOver={e=>e.preventDefault()} onDrop={()=>move(drag.current,i)} className="border-t"><td className="pl-4"><GripVertical size={18} className="cursor-grab text-slate-400"/></td><td className="p-3 font-semibold text-slate-900">{m.text}</td><td className="p-3 text-slate-600"><span className="flex items-center gap-1.5"><CalendarDays size={14}/>{period(m)}</span></td><td className="p-3"><Toggle value={m.is_active!==false} onClick={()=>persist(messages.map(x=>x.id===m.id?{...x,is_active:x.is_active===false}:x))}/></td><td className="p-3"><div className="flex justify-end"><button title="Visualizar" onClick={()=>setPreview(m)} className="p-2"><Eye size={17}/></button><button title="Editar" onClick={()=>setEditing({...m})} className="p-2"><Pencil size={17}/></button><button title="Duplicar" onClick={()=>persist([...messages,{...m,id:crypto.randomUUID(),text:`${m.text} - cópia`}])} className="p-2"><Copy size={17}/></button><button title="Excluir" onClick={()=>confirm('Excluir esta mensagem?')&&persist(messages.filter(x=>x.id!==m.id))} className="p-2 text-red-500"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table>{!messages.length&&<p className="py-10 text-center text-sm text-slate-400">Nenhuma faixa promocional cadastrada.</p>}</div>{busy&&<p className="border-t py-2 text-center text-xs text-slate-400">Salvando alterações...</p>}
 {editing&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 sm:items-center sm:p-4" onClick={()=>setEditing()}><div className="w-full max-w-lg rounded-t-3xl bg-white p-5 sm:rounded-2xl" onClick={e=>e.stopPropagation()}><header className="mb-4 flex justify-between"><h3 className="font-bold">{messages.some(m=>m.id===editing.id)?'Editar mensagem':'Nova mensagem'}</h3><button onClick={()=>setEditing()}><X size={19}/></button></header><textarea value={editing.text} onChange={e=>setEditing(p=>({...p,text:e.target.value}))} rows={3} placeholder="Texto da mensagem promocional" className="w-full resize-none rounded-xl border p-3 text-sm"/><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs text-slate-500">Início<input type="date" value={editing.start_date||''} onChange={e=>setEditing(p=>({...p,start_date:e.target.value}))} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label><label className="text-xs text-slate-500">Fim<input type="date" value={editing.end_date||''} onChange={e=>setEditing(p=>({...p,end_date:e.target.value}))} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label></div><button disabled={!editing.text.trim()||busy} onClick={save} className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>Salvar mensagem</button></div></div>}
 {preview&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={()=>setPreview()}><div className="w-full max-w-xl rounded-2xl p-6 text-center shadow-xl" style={{color:textColor,backgroundColor}}><p className="font-bold">{preview.text}</p></div></div>}</section>}
