import {Router} from 'express';
import {z} from 'zod';
import {query} from '../../db/client.js';
import {requireAuth,requireRoles,type AuthRequest} from '../../auth/middleware.js';

export const blogRouter=Router();
const input=z.object({title:z.string().min(3).max(180),slug:z.string().min(3).max(180).regex(/^[a-z0-9-]+$/),excerpt:z.string().max(500).default(''),content:z.string().min(10),category:z.string().max(60).default('Novidades'),cover_image_url:z.string().max(2000).optional().or(z.literal('')),author_name:z.string().max(100).default('Equipe PEDDI'),author_role:z.string().max(100).default('PEDDI'),status:z.enum(['draft','published']).default('draft'),featured:z.boolean().default(false)});
const view=(row:any)=>({...row,featured:Boolean(row.featured)});

blogRouter.get('/blog',async(_req,res)=>{const rows=await query("SELECT * FROM blog_articles WHERE status='published' ORDER BY featured DESC,published_at DESC NULLS LAST,created_at DESC");res.json({articles:rows.rows.map(view)});});
blogRouter.get('/blog/:slug',async(req,res)=>{const rows=await query("SELECT * FROM blog_articles WHERE slug=$1 AND status='published' LIMIT 1",[req.params.slug]);if(!rows.rowCount)return res.status(404).json({error:'Artigo não encontrado.'});res.json({article:view(rows.rows[0])});});
blogRouter.get('/admin/blog',requireAuth,requireRoles('peddi_admin'),async(_req,res)=>{const rows=await query('SELECT * FROM blog_articles ORDER BY updated_at DESC');res.json({articles:rows.rows.map(view)});});
blogRouter.post('/admin/blog',requireAuth,requireRoles('peddi_admin'),async(req:AuthRequest,res)=>{const parsed=input.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Revise os campos do artigo.'});const d=parsed.data;try{const rows=await query(`INSERT INTO blog_articles(slug,title,excerpt,content,category,cover_image_url,author_name,author_role,status,featured,published_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,CASE WHEN $9='published' THEN now() END,$11) RETURNING *`,[d.slug,d.title,d.excerpt,d.content,d.category,d.cover_image_url||null,d.author_name,d.author_role,d.status,d.featured,req.auth!.userId]);res.status(201).json({article:view(rows.rows[0])});}catch{return res.status(409).json({error:'Já existe um artigo com este endereço.'});}});
blogRouter.patch('/admin/blog/:id',requireAuth,requireRoles('peddi_admin'),async(req,res)=>{const parsed=input.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Revise os campos do artigo.'});const d=parsed.data;try{const rows=await query(`UPDATE blog_articles SET slug=$2,title=$3,excerpt=$4,content=$5,category=$6,cover_image_url=$7,author_name=$8,author_role=$9,status=$10,featured=$11,published_at=CASE WHEN $10='published' THEN COALESCE(published_at,now()) ELSE NULL END,updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,d.slug,d.title,d.excerpt,d.content,d.category,d.cover_image_url||null,d.author_name,d.author_role,d.status,d.featured]);if(!rows.rowCount)return res.status(404).json({error:'Artigo não encontrado.'});res.json({article:view(rows.rows[0])});}catch{return res.status(409).json({error:'Já existe um artigo com este endereço.'});}});
blogRouter.delete('/admin/blog/:id',requireAuth,requireRoles('peddi_admin'),async(req,res)=>{await query('DELETE FROM blog_articles WHERE id=$1',[req.params.id]);res.sendStatus(204);});
