mutation CreateEstablishment($data: Establishment_Data!) @auth(level: USER) {
  establishment_insert(data: $data)
}

mutation UpdateEstablishment($id: UUID!, $data: Establishment_Data!) @auth(level: USER) {
  establishment_update(id: $id, data: $data)
}

mutation DeleteEstablishment($id: UUID!) @auth(level: USER) {
  establishment_delete(id: $id)
}

query GetEstablishment($id: UUID!) @auth(level: PUBLIC, insecureReason: "Establishments are public.") {
  establishment(id: $id) {
    name
    category
    address
    rating
    isOpen
  }
}

query ListEstablishments @auth(level: PUBLIC, insecureReason: "Establishments are public.") {
  establishments {
    name
    category
  }
}

mutation CreateProduct($data: Product_Data!) @auth(level: USER) {
  product_insert(data: $data)
}

mutation UpdateProduct($id: UUID!, $data: Product_Data!) @auth(level: USER) {
  product_update(id: $id, data: $data)
}

mutation DeleteProduct($id: UUID!) @auth(level: USER) {
  product_delete(id: $id)
}

query GetProduct($id: UUID!) @auth(level: PUBLIC, insecureReason: "Products are public.") {
  product(id: $id) {
    name
    price
    description
    establishment { name }
  }
}

query ListProducts @auth(level: PUBLIC, insecureReason: "Products are public.") {
  products {
    name
    price
  }
}

mutation CreateUser($data: User_Data!) @auth(level: USER) {
  user_insert(data: $data)
}

mutation UpdateUser($data: User_Data!) @auth(level: USER) {
  user_update(key: {id_expr: "auth.uid"}, data: $data)
}

mutation DeleteUser @auth(level: USER) {
  user_delete(key: {id_expr: "auth.uid"})
}

query GetUser @auth(level: USER) {
  user(key: {id_expr: "auth.uid"}) {
    name
    email
    role
  }
}

query ListUsers @auth(level: USER) {
  users {
    name
    role
  }
}

mutation CreateOrder($data: Order_Data!) @auth(level: USER) {
  order_insert(data: $data)
}

mutation UpdateOrder($id: UUID!, $data: Order_Data!) @auth(level: USER) {
  order_update(id: $id, data: $data)
}

mutation DeleteOrder($id: UUID!) @auth(level: USER) {
  order_delete(id: $id)
}

query GetOrder($id: UUID!) @auth(level: USER) {
  order(id: $id) {
    status
    totalAmount
    deliveryAddress
  }
}

query ListMyOrders @auth(level: USER) {
  orders(where: {consumerId: {eq_expr: "auth.uid"}}) {
    status
    totalAmount
  }
}

mutation CreateOrderItem($data: OrderItem_Data!) @auth(level: USER) {
  orderItem_insert(data: $data)
}

mutation UpdateOrderItem($id: UUID!, $data: OrderItem_Data!) @auth(level: USER) {
  orderItem_update(id: $id, data: $data)
}

mutation DeleteOrderItem($id: UUID!) @auth(level: USER) {
  orderItem_delete(id: $id)
}

query GetOrderItem($id: UUID!) @auth(level: USER) {
  orderItem(id: $id) {
    quantity
    product { name }
  }
}

query ListOrderItems($orderId: UUID!) @auth(level: USER) {
  orderItems(where: {orderId: {eq: $orderId}}) {
    quantity
    observations
  }
}