extend type Establishment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Establishment", purpose: IMPLICIT_KEY_FIELD)
}
extend type Order {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Order", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Order`.`consumer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  consumerId: UUID! @fdc_generated(from: "Order.consumer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Order`.`courier`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  courierId: UUID @fdc_generated(from: "Order.courier", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Order`.`establishment`. It must match the value of `Establishment`.`id`. See `@ref` for how to customize it.
  """
  establishmentId: UUID! @fdc_generated(from: "Order.establishment", purpose: IMPLICIT_REF_FIELD)
}
extend type OrderItem {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "OrderItem", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `OrderItem`.`order`. It must match the value of `Order`.`id`. See `@ref` for how to customize it.
  """
  orderId: UUID! @fdc_generated(from: "OrderItem.order", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `OrderItem`.`product`. It must match the value of `Product`.`id`. See `@ref` for how to customize it.
  """
  productId: UUID! @fdc_generated(from: "OrderItem.product", purpose: IMPLICIT_REF_FIELD)
}
extend type Product {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Product", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Product`.`establishment`. It must match the value of `Establishment`.`id`. See `@ref` for how to customize it.
  """
  establishmentId: UUID! @fdc_generated(from: "Product.establishment", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
