import {useEffect,useState} from 'react';
import {Edit3,Eye,FileText,Loader2,Plus,Trash2,Upload,X} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {deleteBlogArticle,listAdminBlog,saveBlogArticle} from '@/services/api/blog';
import {Navigate} from 'react-router-dom';
import {useAuth} from '@/lib/AuthContext';
const empty={title:'',slug:'',excerpt:'',content:'',category:'Novidades',cover_image_url:'',author_name:'Equipe PEDDI',author_role:'PEDDI',status:'draft',featured:false};
const slugify=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export default function BlogAdmin(){
 const{user}=useAuth();
 const[items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(),[open,setOpen]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const load=()=>listAdminBlog().then(r=>setItems(r.articles)).catch(e=>setError(e.message));useEffect(load,[]);const set=(key,value)=>setForm(previous=>({...previous,[key]:value}));
 const start=article=>{setEditing(article?.id);setForm(article?{...empty,...article}:empty);setOpen(true);setError('')};
 const save=async event=>{event.preventDefault();setSaving(true);setError('');try{await saveBlogArticle({...form,slug:form.slug||slugify(form.title)},editing);setOpen(false);load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const remove=async article=>{if(!confirm(`Excluir "${article.title}"?`))return;await deleteBlogArticle(article.id);load()};
 const uploadCover=async event=>{const file=event.target.files?.[0];if(!file)return;setUploading(true);setError('');try{const{file_url}=await base44.integrations.Core.UploadFile({file});set('cover_image_url',file_url)}catch(e){setError(e.message)}finally{setUploading(false);event.target.value=''}};
 if(user?.role!=='peddi_admin')return <Navigate replace to="/admin"/>;
 return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Blog da PEDDI</h1><p className="text-sm text-muted-foreground">Crie manchetes, novidades e artigos públicos da plataforma.</p></div><button onClick={()=>start()} className="flex min-h-11 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-white"><Plus size={18}/>Novo artigo</button></header>{error&&!open&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-600">{error}</p>}<div className="grid gap-4">{items.map(article=><article key={article.id} className="flex flex-col gap-4 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center">{article.cover_image_url?<img src={article.cover_image_url} alt="" className="h-24 w-full rounded-xl object-cover sm:w-36"/>:<div className="flex h-24 w-full items-center justify-center rounded-xl bg-primary/10 text-primary sm:w-36"><FileText/></div>}<div className="min-w-0 flex-1"><div className="flex gap-2 text-xs"><span className="rounded-full bg-primary/10 px-2 py-1 font-bold text-primary">{article.category}</span><span className={`rounded-full px-2 py-1 font-bold ${article.status==='published'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600'}`}>{article.status==='published'?'Publicado':'Rascunho'}</span>{article.featured&&<span className="rounded-full bg-amber-100 px-2 py-1 font-bold text-amber-700">Manchete</span>}</div><h2 className="mt-2 truncate font-bold">{article.title}</h2><p className="truncate text-sm text-muted-foreground">{article.excerpt}</p></div><div className="flex gap-2"><a href={`/blog/${article.slug}`} target="_blank" rel="noreferrer" className="rounded-lg border p-3"><Eye size={17}/></a><button onClick={()=>start(article)} className="rounded-lg border p-3"><Edit3 size={17}/></button><button onClick={()=>remove(article)} className="rounded-lg border border-red-200 p-3 text-red-500"><Trash2 size={17}/></button></div></article>)}</div>
 {open&&<div className="fixed inset-0 z-[80] flex justify-end bg-black/40"><form onSubmit={save} className="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{editing?'Editar artigo':'Novo artigo'}</h2><button type="button" onClick={()=>setOpen(false)} className="p-2"><X/></button></div><div className="mt-6 grid gap-4"><label className="text-sm font-semibold">Título<input required value={form.title} onChange={e=>{set('title',e.target.value);if(!editing)set('slug',slugify(e.target.value))}} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-semibold">Endereço do artigo<input required value={form.slug} onChange={e=>set('slug',slugify(e.target.value))} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Categoria<input value={form.category} onChange={e=>set('category',e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-semibold">Status<select value={form.status} onChange={e=>set('status',e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"><option value="draft">Rascunho</option><option value="published">Publicado</option></select></label></div><label className="text-sm font-semibold">Resumo<textarea required value={form.excerpt} onChange={e=>set('excerpt',e.target.value)} className="mt-1 h-24 w-full rounded-xl border p-3 font-normal"/></label>
 <div className="rounded-xl border p-3"><span className="text-sm font-semibold">Imagem de capa</span>{form.cover_image_url&&<img src={form.cover_image_url} alt="Prévia da capa" className="mt-2 aspect-[16/7] w-full rounded-xl object-cover"/>}<div className="mt-3 flex flex-wrap gap-2"><label className="flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border px-4 text-sm font-semibold">{uploading?<Loader2 className="animate-spin" size={17}/>:<Upload size={17}/>}Enviar imagem<input type="file" accept="image/*" onChange={uploadCover} disabled={uploading} className="hidden"/></label><input value={form.cover_image_url} onChange={e=>set('cover_image_url',e.target.value)} placeholder="Ou cole uma URL" className="h-11 min-w-0 flex-1 rounded-xl border px-3 font-normal"/></div></div>
 <label className="text-sm font-semibold">Conteúdo<textarea required value={form.content} onChange={e=>set('content',e.target.value)} placeholder="Separe os parágrafos com uma linha em branco." className="mt-1 min-h-72 w-full rounded-xl border p-3 font-normal leading-6"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Autor<input value={form.author_name} onChange={e=>set('author_name',e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-semibold">Cargo<input value={form.author_role} onChange={e=>set('author_role',e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3 font-normal"/></label></div><label className="flex items-center gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)}/>Exibir como manchete principal</label>{error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={saving||uploading} className="min-h-12 rounded-xl bg-primary font-bold text-white disabled:opacity-50">{saving?'Salvando...':'Salvar artigo'}</button></div></form></div>}</div>}
