import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, ChevronRight, Search } from 'lucide-react';
import { base44 } from '@/api/base44Client';

const starter=[
 {id:'start',title:'Primeiros passos no PEDDI',category:'Primeiros passos',summary:'Configure sua loja, horários e formas de atendimento.',content:'Comece em Configurações: revise os dados da loja, horários, endereço, formas de pagamento e áreas de entrega. Depois cadastre categorias e produtos para publicar o cardápio.',order:1,status:'published'},
 {id:'orders',title:'Como acompanhar pedidos',category:'Pedidos',summary:'Entenda os status e a operação do Kanban.',content:'Use Lista para consulta e Kanban para operação. Abra o pedido para conferir itens, pagamento e entrega. Atualize o status conforme o preparo avança.',order:2,status:'published'},
 {id:'products',title:'Cadastrar e editar produtos',category:'Produtos',summary:'Organize informações, preços, fotos e estoque.',content:'Em Produtos, crie um item e percorra as seções da edição. Salve ao terminar. Produtos pausados ficam ocultos do cardápio sem serem excluídos.',order:3,status:'published'},
 {id:'pdv',title:'Lançar uma venda pelo PDV',category:'PDV',summary:'Crie pedidos de balcão, retirada ou entrega.',content:'Selecione o tipo do pedido, adicione os produtos, informe o pagamento e lance o pedido. Para mesas, você também pode manter a comanda aberta.',order:4,status:'published'},
];
export default function HelpCenter(){
 const [articles,setArticles]=useState([]),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[selected,setSelected]=useState(null);
 useEffect(()=>{base44.entities.HelpArticle.filter({status:'published'},'order').then(rows=>setArticles(rows.length?rows:starter)).catch(()=>setArticles(starter));},[]);
 const categories=['Todos',...new Set(articles.map(a=>a.category))];
 const visible=useMemo(()=>articles.filter(a=>(category==='Todos'||a.category===category)&&(!query||`${a.title} ${a.summary} ${a.content}`.toLowerCase().includes(query.toLowerCase()))),[articles,category,query]);
 if(selected)return <div className="mx-auto max-w-4xl"><button onClick={()=>setSelected(null)} className="mb-5 flex min-h-11 items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft size={18}/>Voltar à Central de ajuda</button><article className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-9"><span className="text-xs font-bold uppercase tracking-wider text-primary">{selected.category}</span><h1 className="mt-2 text-3xl font-bold text-gray-900">{selected.title}</h1><p className="mt-3 text-gray-500">{selected.summary}</p><div className="mt-7 whitespace-pre-line border-t border-gray-100 pt-7 leading-7 text-gray-700">{selected.content}</div></article></div>;
 return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Central de ajuda</h1><p className="mt-1 text-sm text-gray-500">Tutoriais, dúvidas frequentes e orientações para sua operação.</p></header><div className="relative max-w-2xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar uma dúvida ou tutorial..." className="h-12 w-full rounded-xl border border-gray-200 bg-white pl-12 pr-4 outline-none focus:border-primary"/></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${category===c?'bg-primary text-white':'border border-gray-200 bg-white text-gray-600'}`}>{c}</button>)}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="group rounded-2xl border border-gray-200 bg-white p-5 text-left transition hover:border-primary/40 hover:shadow-md"><span className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><BookOpen size={21}/></span><span className="text-xs font-bold uppercase tracking-wide text-primary">{a.category}</span><strong className="mt-2 block text-base text-gray-900">{a.title}</strong><span className="mt-2 block text-sm leading-6 text-gray-500">{a.summary}</span><span className="mt-5 flex items-center gap-1 text-sm font-semibold text-primary">Ler artigo <ChevronRight size={16}/></span></button>)}</div>{!visible.length&&<p className="rounded-2xl border border-dashed border-gray-300 p-10 text-center text-gray-500">Nenhum conteúdo encontrado.</p>}</div>;
}
