type Establishment @table {
  name: String!
  category: String!
  address: String!
  rating: Float
  isOpen: Boolean
}

type Product @table {
  name: String!
  price: Float!
  description: String
  imageUrl: String
  establishment: Establishment!
}

type User @table {
  name: String!
  email: String!
  role: String!
  phoneNumber: String
  rating: Float
}

type Order @table {
  status: String!
  totalAmount: Float!
  deliveryAddress: String
  consumer: User!
  establishment: Establishment!
  courier: User
}

type OrderItem @table {
  quantity: Int!
  observations: String
  order: Order!
  product: Product!
}